
# ------------------
#      General
# ------------------

# Whether to expect a bungee instance to interact with. This is used to
# fix several issues inherit with using using this plugin on BungeeCord
# servers.
bungee-forward: false

# The index to start allocating map IDs at. Most of the time, you will
# not need to touch this variable, however, if you are running servers
# with more than one isntance of the consoles plugin, it is suggested
# to give a new index (about 10,000 larger).
#
# Do not set this variable close to 65536, as it could cause constant
# client disconnects if there are a lot of consoles in your server.
starting-map-index: 5000

# Debug mode. Useful for developers, this option will print information
# about canvases being created and removed, and will raise more exceptions
# to the console rather than ignoring them.
debug-mode: false

# This is the range (in blocks) that a player must be in order to
# interact with a console
interact-range: 6